
var YaneuraOu_HalfKPvm_noeval = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(YaneuraOu_HalfKPvm_noeval) {
  YaneuraOu_HalfKPvm_noeval = YaneuraOu_HalfKPvm_noeval || {};


function d(){h.buffer!=q&&r(h.buffer);return aa}function v(){h.buffer!=q&&r(h.buffer);return ba}function w(){h.buffer!=q&&r(h.buffer);return ca}function da(){h.buffer!=q&&r(h.buffer);return ea}null;var A;A||(A=typeof YaneuraOu_HalfKPvm_noeval !== 'undefined' ? YaneuraOu_HalfKPvm_noeval : {});var fa,ha;A.ready=new Promise(function(a,b){fa=a;ha=b});
(function(){function a(){var g=e.shift();if(!b&&void 0!==g){if("quit"===g)return A.terminate();var l=A.ccall("usi_command","number",["string"],[g]);l&&e.unshift(g);f=l?2*f:1;setTimeout(a,f)}}var b=!1,c=[];A.print=function(g){0===c.length?console.log(g):setTimeout(function(){for(var l=0;l<c.length;l++)c[l](g)})};A.addMessageListener=function(g){c.push(g)};A.removeMessageListener=function(g){g=c.indexOf(g);0<=g&&c.splice(g,1)};A.terminate=function(){b=!0;B.xb()};var e=[],f=1;A.postMessage=function(g){e.push(g)};
A.postRun=function(){A.postMessage=function(g){e.push(g);1===e.length&&a()};a()}})();var ia=Object.assign({},A),ja=[],ka="./this.program",la=(a,b)=>{throw b;},ma="object"==typeof window,C="function"==typeof importScripts,F="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,G=A.ENVIRONMENT_IS_PTHREAD||!1,H="";function na(a){return A.locateFile?A.locateFile(a,H):H+a}var oa,pa,qa,fs,ra,sa;
if(F){H=C?require("path").dirname(H)+"/":__dirname+"/";sa=()=>{ra||(fs=require("fs"),ra=require("path"))};oa=function(b,c){sa();b=ra.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};qa=b=>{b=oa(b,!0);b.buffer||(b=new Uint8Array(b));return b};pa=(b,c,e)=>{sa();b=ra.normalize(b);fs.readFile(b,function(f,g){f?e(f):c(g.buffer)})};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof ta))throw b;});process.on("unhandledRejection",
function(b){throw b;});la=(b,c)=>{if(ua())throw process.exitCode=b,c;c instanceof ta||I("exiting due to exception: "+c);process.exit(b)};A.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(ma||C)C?H=self.location.href:"undefined"!=typeof document&&document.currentScript&&(H=document.currentScript.src),
_scriptDir&&(H=_scriptDir),0!==H.indexOf("blob:")?H=H.substr(0,H.replace(/[?#].*/,"").lastIndexOf("/")+1):H="",F||(oa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},C&&(qa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=
c;e.send(null)});F&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var va=console.log.bind(console),wa=console.warn.bind(console);F&&(sa(),va=a=>fs.writeSync(1,a+"\n"),wa=a=>fs.writeSync(2,a+"\n"));var xa=A.print||va,I=A.printErr||wa;Object.assign(A,ia);ia=null;A.arguments&&(ja=A.arguments);A.thisProgram&&(ka=A.thisProgram);A.quit&&(la=A.quit);var ya,za;A.wasmBinary&&(za=A.wasmBinary);var noExitRuntime=A.noExitRuntime||!0;"object"!=typeof WebAssembly&&K("no native wasm support detected");
var h,Aa,Ba=!1;function Ca(a){var b=new TextDecoder(a);this.decode=c=>{c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Da="undefined"!=typeof TextDecoder?new Ca("utf8"):void 0;
function L(a,b,c){b>>>=0;var e=b+c;for(c=b;a[c>>>0]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&Da)return Da.decode(a.subarray(b>>>0,c>>>0));for(e="";b<c;){var f=a[b++>>>0];if(f&128){var g=a[b++>>>0]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++>>>0]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++>>>0]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}
function M(a){return(a>>>=0)?L(v(),a,void 0):""}
function N(a,b,c,e){c>>>=0;if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=e)break;b[c++>>>0]=l}else{if(2047>=l){if(c+1>=e)break;b[c++>>>0]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++>>>0]=224|l>>12}else{if(c+3>=e)break;b[c++>>>0]=240|l>>18;b[c++>>>0]=128|l>>12&63}b[c++>>>0]=128|l>>6&63}b[c++>>>0]=128|l&63}}b[c>>>0]=0;return c-f}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!=typeof TextDecoder&&new Ca("utf-16le");function Fa(a){var b=Ea(a)+1,c=O(b);N(a,d(),c,b);return c}function Ga(a,b){d().set(a,b>>>0)}var q,aa,ba,Ha,ca,ea;G&&(q=A.buffer);
function r(a){q=a;A.HEAP8=aa=new Int8Array(a);A.HEAP16=Ha=new Int16Array(a);A.HEAP32=ca=new Int32Array(a);A.HEAPU8=ba=new Uint8Array(a);A.HEAPU16=new Uint16Array(a);A.HEAPU32=new Uint32Array(a);A.HEAPF32=new Float32Array(a);A.HEAPF64=ea=new Float64Array(a)}var Ia=A.INITIAL_MEMORY||100663296;
if(G)h=A.wasmMemory,q=A.buffer;else if(A.wasmMemory)h=A.wasmMemory;else if(h=new WebAssembly.Memory({initial:Ia/65536,maximum:65536,shared:!0}),!(h.buffer instanceof SharedArrayBuffer))throw I("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),F&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");h&&(q=h.buffer);Ia=q.byteLength;r(q);var Ja,Ka=[],La=[],Ma=[],Na=[],Oa=0;function ua(){return noExitRuntime||0<Oa}function Pa(){G||(A.noFSInit||P.Ba.mb||P.Ba(),P.Rb=!1,Qa(La))}function Ra(){var a=A.preRun.shift();Ka.unshift(a)}var Q=0,Sa=null,Ta=null;function Ua(){Q++;A.monitorRunDependencies&&A.monitorRunDependencies(Q)}function Va(){Q--;A.monitorRunDependencies&&A.monitorRunDependencies(Q);if(0==Q&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}
A.preloadedImages={};A.preloadedAudios={};function K(a){if(G)postMessage({cmd:"onAbort",arg:a});else if(A.onAbort)A.onAbort(a);a="Aborted("+a+")";I(a);Ba=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ha(a);throw a;}function Wa(){return R.startsWith("data:application/octet-stream;base64,")}var R;R="yaneuraou.halfkpvm.noeval.wasm";Wa()||(R=na(R));
function Xa(){var a=R;try{if(a==R&&za)return new Uint8Array(za);if(qa)return qa(a);throw"both async and sync fetching of the wasm failed";}catch(b){K(b)}}function Ya(){return za||!ma&&!C||"function"!=typeof fetch?Promise.resolve().then(function(){return Xa()}):fetch(R,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+R+"'";return a.arrayBuffer()}).catch(function(){return Xa()})}var S,Za,$a={};
function Qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(A);else{var c=b.dd;"number"==typeof c?void 0===b.Ha?ab(c)():ab(c)(b.Ha):c(void 0===b.Ha?null:b.Ha)}}}function bb(a){var b=cb();a=a();db(b);return a}function eb(a){var b=B.qa[a];b&&(w()[a>>2>>>0]=0,B.Vb(b.worker))}function fb(a){a instanceof ta||"unwind"==a||la(1,a)}
var B={ra:[],Qa:[],$a:[],Ba:function(){G?B.wc():B.vc()},vc:function(){for(var a=0;32>a;++a)B.Bb()},wc:function(){B.receiveObjectTransfer=B.Ic;B.threadInit=B.Xb;B.setExitStatus=B.Mc;noExitRuntime=!1},qa:{},Mc:function(){},xb:function(){for(var a in B.qa){var b=B.qa[a];b&&b.worker&&B.Vb(b.worker)}for(a=0;a<B.ra.length;++a)B.ra[a].terminate();B.ra=[]},Vb:function(a){B.Kc(function(){delete B.qa[a.Da.yb];B.ra.push(a);B.Qa.splice(B.Qa.indexOf(a),1);gb(a.Da.yb);a.Da=void 0})},Kc:function(a){w()[hb>>>2]=
0;try{a()}finally{w()[hb>>>2]=1}},Ic:function(){},Xb:function(){for(var a in B.$a)if(B.$a.hasOwnProperty(a))B.$a[a]()},Sb:function(a,b){a.onmessage=c=>{c=c.data;var e=c.cmd;a.Da&&(B.nc=a.Da.yb);if(c.targetThread&&c.targetThread!=ib()){var f=B.qa[c.vd];f?f.worker.postMessage(c,c.transferList):I('Internal error! Worker sent a message "'+e+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)jb();else if("spawnThread"===e)kb(c);else if("cleanupThread"===
e)eb(c.thread);else if("killThread"===e)c=c.thread,w()[c>>2>>>0]=0,e=B.qa[c],delete B.qa[c],e.worker.terminate(),gb(c),B.Qa.splice(B.Qa.indexOf(e.worker),1),e.worker.Da=void 0;else if("cancelThread"===e)B.qa[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===e)a.loaded=!0,b&&b(a),a.Pa&&(a.Pa(),delete a.Pa);else if("print"===e)xa("Thread "+c.threadId+": "+c.text);else if("printErr"===e)I("Thread "+c.threadId+": "+c.text);else if("alert"===e)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===
c.target)a.postMessage(c);else if("onAbort"===e){if(A.onAbort)A.onAbort(c.arg)}else I("worker sent an unknown command "+e);B.nc=void 0};a.onerror=c=>{I("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};F&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:A.mainScriptUrlOrBlob||_scriptDir,wasmMemory:h,wasmModule:Aa})},Bb:function(){var a=na("yaneuraou.halfkpvm.noeval.worker.js");
B.ra.push(new Worker(a))},tc:function(){0==B.ra.length&&(B.Bb(),B.Sb(B.ra[0]));return B.ra.pop()}};A.establishStackSpace=function(){var a=ib(),b=w()[a+44>>2>>>0];a=w()[a+48>>2>>>0];lb(b,b-a);db(b)};function mb(a){if(G)return T(1,0,a);try{nb(a)}catch(b){fb(b)}}var ob=[];function ab(a){var b=ob[a];b||(a>=ob.length&&(ob.length=a+1),ob[a]=b=Ja.get(a));return b}A.invokeEntryPoint=function(a,b){return ab(a)(b)};var pb;
pb=F?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:G?()=>performance.now()-A.__performance_now_clock_drift:()=>performance.now();function kb(a){var b=B.tc();if(!b)return 6;B.Qa.push(b);var c=B.qa[a.sb]={worker:b,yb:a.sb};b.Da=c;var e={cmd:"run",start_routine:a.Nc,arg:a.Ha,threadInfoStruct:a.sb};b.Pa=()=>{e.time=performance.now();b.postMessage(e,a.Tc)};b.loaded&&(b.Pa(),delete b.Pa);return 0}
function qb(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function rb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=qb(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function sb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function U(a){if("/"===a)return"/";a=rb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function V(a,b){return rb(a+"/"+b)}
function tb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(F)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){K("randomDevice")}}
function W(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:P.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=qb(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function ub(a,b){function c(l){for(var n=0;n<l.length&&""===l[n];n++);for(var t=l.length-1;0<=t&&""===l[t];t--);return n>t?[]:l.slice(n,t-n+1)}a=W(a).substr(1);b=W(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}var vb=[];function wb(a,b){vb[a]={input:[],output:[],Ca:b};P.wb(a,xb)}
var xb={open:function(a){var b=vb[a.node.rdev];if(!b)throw new P.$(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ca.flush(a.tty)},flush:function(a){a.tty.Ca.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.Ca.Nb)throw new P.$(60);for(var f=0,g=0;g<e;g++){try{var l=a.tty.Ca.Nb(a.tty)}catch(n){throw new P.$(29);}if(void 0===l&&0===f)throw new P.$(6);if(null===l||void 0===l)break;f++;b[c+g]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.Ca.tb)throw new P.$(60);
try{for(var f=0;f<e;f++)a.tty.Ca.tb(a.tty,b[c+f])}catch(g){throw new P.$(29);}e&&(a.node.timestamp=Date.now());return f}},zb={Nb:function(a){if(!a.input.length){var b=null;if(F){var c=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(f){if(f.toString().includes("EOF"))e=0;else throw f;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=yb(b,!0)}return a.input.shift()},tb:function(a,b){null===b||10===b?(xa(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(xa(L(a.output,0)),a.output=[])}},Ab={tb:function(a,b){null===b||10===b?(I(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(I(L(a.output,0)),a.output=[])}},X={pa:null,ga:function(){return X.createNode(null,"/",16895,0)},createNode:function(a,
b,c,e){if(P.xc(c)||P.isFIFO(c))throw new P.$(63);X.pa||(X.pa={dir:{node:{ma:X.aa.ma,ia:X.aa.ia,lookup:X.aa.lookup,ta:X.aa.ta,rename:X.aa.rename,unlink:X.aa.unlink,rmdir:X.aa.rmdir,readdir:X.aa.readdir,symlink:X.aa.symlink},stream:{na:X.da.na}},file:{node:{ma:X.aa.ma,ia:X.aa.ia},stream:{na:X.da.na,read:X.da.read,write:X.da.write,Ga:X.da.Ga,La:X.da.La,Oa:X.da.Oa}},link:{node:{ma:X.aa.ma,ia:X.aa.ia,readlink:X.aa.readlink},stream:{}},Db:{node:{ma:X.aa.ma,ia:X.aa.ia},stream:P.ec}});c=P.createNode(a,b,
c,e);P.ha(c.mode)?(c.aa=X.pa.dir.node,c.da=X.pa.dir.stream,c.ba={}):P.isFile(c.mode)?(c.aa=X.pa.file.node,c.da=X.pa.file.stream,c.fa=0,c.ba=null):P.Ka(c.mode)?(c.aa=X.pa.link.node,c.da=X.pa.link.stream):P.Va(c.mode)&&(c.aa=X.pa.Db.node,c.da=X.pa.Db.stream);c.timestamp=Date.now();a&&(a.ba[b]=c,a.timestamp=c.timestamp);return c},ed:function(a){return a.ba?a.ba.subarray?a.ba.subarray(0,a.fa):new Uint8Array(a.ba):new Uint8Array(0)},Jb:function(a,b){b>>>=0;var c=a.ba?a.ba.length:0;c>=b||(b=Math.max(b,
c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ba,a.ba=new Uint8Array(b),0<a.fa&&a.ba.set(c.subarray(0,a.fa),0))},Jc:function(a,b){b>>>=0;if(a.fa!=b)if(0==b)a.ba=null,a.fa=0;else{var c=a.ba;a.ba=new Uint8Array(b);c&&a.ba.set(c.subarray(0,Math.min(b,a.fa)));a.fa=b}},aa:{ma:function(a){var b={};b.dev=P.Va(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;P.ha(a.mode)?b.size=4096:P.isFile(a.mode)?b.size=a.fa:P.Ka(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);
b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.cc=4096;b.blocks=Math.ceil(b.size/b.cc);return b},ia:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.Jc(a,b.size)},lookup:function(){throw P.ib[44];},ta:function(a,b,c,e){return X.createNode(a,b,c,e)},rename:function(a,b,c){if(P.ha(a.mode)){try{var e=P.sa(b,c)}catch(g){}if(e)for(var f in e.ba)throw new P.$(55);}delete a.parent.ba[a.name];a.parent.timestamp=Date.now();a.name=
c;b.ba[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.ba[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=P.sa(a,b),e;for(e in c.ba)throw new P.$(55);delete a.ba[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.ba)a.ba.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=X.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!P.Ka(a.mode))throw new P.$(28);return a.link}},da:{read:function(a,b,c,e,f){var g=a.node.ba;
if(f>=a.node.fa)return 0;a=Math.min(a.node.fa-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write:function(a,b,c,e,f,g){b.buffer===d().buffer&&(g=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ba||a.ba.subarray)){if(g)return a.ba=b.subarray(c,c+e),a.fa=e;if(0===a.fa&&0===f)return a.ba=b.slice(c,c+e),a.fa=e;if(f+e<=a.fa)return a.ba.set(b.subarray(c,c+e),f),e}X.Jb(a,f+e);if(a.ba.subarray&&b.subarray)a.ba.set(b.subarray(c,c+e),
f);else for(g=0;g<e;g++)a.ba[f+g]=b[c+g];a.fa=Math.max(a.fa,f+e);return e},na:function(a,b,c){1===c?b+=a.position:2===c&&P.isFile(a.node.mode)&&(b+=a.node.fa);if(0>b)throw new P.$(28);return b},Ga:function(a,b,c){X.Jb(a.node,b+c);a.node.fa=Math.max(a.node.fa,b+c)},La:function(a,b,c,e,f,g){if(0!==b)throw new P.$(28);if(!P.isFile(a.node.mode))throw new P.$(43);a=a.node.ba;if(g&2||a.buffer!==q){if(0<e||e+c<a.length)a.subarray?a=a.subarray(e,e+c):a=Array.prototype.slice.call(a,e,e+c);e=!0;g=65536*Math.ceil(c/
65536);(c=Bb(65536,g))?v().fill(0,c,c+g):c=0;if(!c)throw new P.$(48);c>>>=0;d().set(a,c>>>0)}else e=!1,c=a.byteOffset;return{rd:c,Vc:e}},Oa:function(a,b,c,e,f){if(!P.isFile(a.node.mode))throw new P.$(43);if(f&2)return 0;X.da.write(a,b,0,e,c,!1);return 0}}};function Cb(a,b,c){var e="al "+a;pa(a,function(f){f||K('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));e&&Va()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Ua()}
var P={root:null,Na:[],Gb:{},streams:[],Dc:1,oa:null,Fb:"/",mb:!1,Rb:!0,$:null,ib:{},qc:null,Za:0,ea:(a,b={})=>{a=W(P.cwd(),a);if(!a)return{path:"",node:null};b=Object.assign({hb:!0,vb:0},b);if(8<b.vb)throw new P.$(32);a=qb(a.split("/").filter(l=>!!l),!1);for(var c=P.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;c=P.sa(c,a[f]);e=V(e,a[f]);P.xa(c)&&(!g||g&&b.hb)&&(c=c.Ma.root);if(!g||b.la)for(g=0;P.Ka(c.mode);)if(c=P.readlink(e),e=W(sb(e),c),c=P.ea(e,{vb:b.vb+1}).node,40<
g++)throw new P.$(32);}return{path:e,node:c}},wa:a=>{for(var b;;){if(P.Wa(a))return a=a.ga.Tb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},lb:(a,b)=>{for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%P.oa.length},Pb:a=>{var b=P.lb(a.parent.id,a.name);a.za=P.oa[b];P.oa[b]=a},Qb:a=>{var b=P.lb(a.parent.id,a.name);if(P.oa[b]===a)P.oa[b]=a.za;else for(b=P.oa[b];b;){if(b.za===a){b.za=a.za;break}b=b.za}},sa:(a,b)=>{var c=P.Ac(a);if(c)throw new P.$(c,
a);for(c=P.oa[P.lb(a.id,b)];c;c=c.za){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return P.lookup(a,b)},createNode:(a,b,c,e)=>{a=new P.Yb(a,b,c,e);P.Pb(a);return a},gb:a=>{P.Qb(a)},Wa:a=>a===a.parent,xa:a=>!!a.Ma,isFile:a=>32768===(a&61440),ha:a=>16384===(a&61440),Ka:a=>40960===(a&61440),Va:a=>8192===(a&61440),xc:a=>24576===(a&61440),isFIFO:a=>4096===(a&61440),isSocket:a=>49152===(a&49152),rc:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Cc:a=>{var b=P.rc[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+
a);return b},Kb:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Aa:(a,b)=>{if(P.Rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Ac:a=>{var b=P.Aa(a,"x");return b?b:a.aa.lookup?0:2},rb:(a,b)=>{try{return P.sa(a,b),20}catch(c){}return P.Aa(a,"wx")},Xa:(a,b,c)=>{try{var e=P.sa(a,b)}catch(f){return f.ka}if(a=P.Aa(a,"wx"))return a;if(c){if(!P.ha(e.mode))return 54;if(P.Wa(e)||P.wa(e)===P.cwd())return 10}else if(P.ha(e.mode))return 31;
return 0},Bc:(a,b)=>a?P.Ka(a.mode)?32:P.ha(a.mode)&&("r"!==P.Kb(b)||b&512)?31:P.Aa(a,P.Kb(b)):44,Zb:4096,Ec:(a=0,b=P.Zb)=>{for(;a<=b;a++)if(!P.streams[a])return a;throw new P.$(33);},Ia:a=>P.streams[a],mc:(a,b,c)=>{P.eb||(P.eb=function(){},P.eb.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});a=Object.assign(new P.eb,a);b=P.Ec(b,c);a.fd=b;return P.streams[b]=a},fc:a=>{P.streams[a]=null},ec:{open:a=>{a.da=P.sc(a.node.rdev).da;a.da.open&&a.da.open(a)},na:()=>{throw new P.$(70);
}},qb:a=>a>>8,kd:a=>a&255,ya:(a,b)=>a<<8|b,wb:(a,b)=>{P.Gb[a]={da:b}},sc:a=>P.Gb[a],Mb:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Na)}return b},Wb:(a,b)=>{function c(l){P.Za--;return b(l)}function e(l){if(l){if(!e.oc)return e.oc=!0,c(l)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);P.Za++;1<P.Za&&I("warning: "+P.Za+" FS.syncfs operations in flight at once, probably just doing extra work");var f=P.Mb(P.root.ga),g=0;f.forEach(l=>{if(!l.type.Wb)return e(null);
l.type.Wb(l,a,e)})},ga:(a,b,c)=>{var e="/"===c,f=!c;if(e&&P.root)throw new P.$(10);if(!e&&!f){var g=P.ea(c,{hb:!1});c=g.path;g=g.node;if(P.xa(g))throw new P.$(10);if(!P.ha(g.mode))throw new P.$(54);}b={type:a,pd:b,Tb:c,Na:[]};a=a.ga(b);a.ga=b;b.root=a;e?P.root=a:g&&(g.Ma=b,g.ga&&g.ga.Na.push(b));return a},xd:a=>{a=P.ea(a,{hb:!1});if(!P.xa(a.node))throw new P.$(28);a=a.node;var b=a.Ma,c=P.Mb(b);Object.keys(P.oa).forEach(e=>{for(e=P.oa[e];e;){var f=e.za;c.includes(e.ga)&&P.gb(e);e=f}});a.Ma=null;a.ga.Na.splice(a.ga.Na.indexOf(b),
1)},lookup:(a,b)=>a.aa.lookup(a,b),ta:(a,b,c)=>{var e=P.ea(a,{parent:!0}).node;a=U(a);if(!a||"."===a||".."===a)throw new P.$(28);var f=P.rb(e,a);if(f)throw new P.$(f);if(!e.aa.ta)throw new P.$(63);return e.aa.ta(e,a,b,c)},create:(a,b)=>P.ta(a,(void 0!==b?b:438)&4095|32768,0),mkdir:(a,b)=>P.ta(a,(void 0!==b?b:511)&1023|16384,0),md:(a,b)=>{a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{P.mkdir(c,b)}catch(f){if(20!=f.ka)throw f;}}},Ya:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=
438);return P.ta(a,b|8192,c)},symlink:(a,b)=>{if(!W(a))throw new P.$(44);var c=P.ea(b,{parent:!0}).node;if(!c)throw new P.$(44);b=U(b);var e=P.rb(c,b);if(e)throw new P.$(e);if(!c.aa.symlink)throw new P.$(63);return c.aa.symlink(c,b,a)},rename:(a,b)=>{var c=sb(a),e=sb(b),f=U(a),g=U(b);var l=P.ea(a,{parent:!0});var n=l.node;l=P.ea(b,{parent:!0});l=l.node;if(!n||!l)throw new P.$(44);if(n.ga!==l.ga)throw new P.$(75);var t=P.sa(n,f);a=ub(a,e);if("."!==a.charAt(0))throw new P.$(28);a=ub(b,c);if("."!==a.charAt(0))throw new P.$(55);
try{var m=P.sa(l,g)}catch(p){}if(t!==m){b=P.ha(t.mode);if(f=P.Xa(n,f,b))throw new P.$(f);if(f=m?P.Xa(l,g,b):P.rb(l,g))throw new P.$(f);if(!n.aa.rename)throw new P.$(63);if(P.xa(t)||m&&P.xa(m))throw new P.$(10);if(l!==n&&(f=P.Aa(n,"w")))throw new P.$(f);P.Qb(t);try{n.aa.rename(t,l,g)}catch(p){throw p;}finally{P.Pb(t)}}},rmdir:a=>{var b=P.ea(a,{parent:!0}).node;a=U(a);var c=P.sa(b,a),e=P.Xa(b,a,!0);if(e)throw new P.$(e);if(!b.aa.rmdir)throw new P.$(63);if(P.xa(c))throw new P.$(10);b.aa.rmdir(b,a);P.gb(c)},
readdir:a=>{a=P.ea(a,{la:!0}).node;if(!a.aa.readdir)throw new P.$(54);return a.aa.readdir(a)},unlink:a=>{var b=P.ea(a,{parent:!0}).node;if(!b)throw new P.$(44);a=U(a);var c=P.sa(b,a),e=P.Xa(b,a,!1);if(e)throw new P.$(e);if(!b.aa.unlink)throw new P.$(63);if(P.xa(c))throw new P.$(10);b.aa.unlink(b,a);P.gb(c)},readlink:a=>{a=P.ea(a).node;if(!a)throw new P.$(44);if(!a.aa.readlink)throw new P.$(28);return W(P.wa(a.parent),a.aa.readlink(a))},stat:(a,b)=>{a=P.ea(a,{la:!b}).node;if(!a)throw new P.$(44);if(!a.aa.ma)throw new P.$(63);
return a.aa.ma(a)},lstat:a=>P.stat(a,!0),chmod:(a,b,c)=>{a="string"==typeof a?P.ea(a,{la:!c}).node:a;if(!a.aa.ia)throw new P.$(63);a.aa.ia(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{P.chmod(a,b,!0)},fchmod:(a,b)=>{a=P.Ia(a);if(!a)throw new P.$(8);P.chmod(a.node,b)},chown:(a,b,c,e)=>{a="string"==typeof a?P.ea(a,{la:!e}).node:a;if(!a.aa.ia)throw new P.$(63);a.aa.ia(a,{timestamp:Date.now()})},lchown:(a,b,c)=>{P.chown(a,b,c,!0)},fchown:(a,b,c)=>{a=P.Ia(a);if(!a)throw new P.$(8);
P.chown(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new P.$(28);a="string"==typeof a?P.ea(a,{la:!0}).node:a;if(!a.aa.ia)throw new P.$(63);if(P.ha(a.mode))throw new P.$(31);if(!P.isFile(a.mode))throw new P.$(28);var c=P.Aa(a,"w");if(c)throw new P.$(c);a.aa.ia(a,{size:b,timestamp:Date.now()})},cd:(a,b)=>{a=P.Ia(a);if(!a)throw new P.$(8);if(0===(a.flags&2097155))throw new P.$(28);P.truncate(a.node,b)},yd:(a,b,c)=>{a=P.ea(a,{la:!0}).node;a.aa.ia(a,{timestamp:Math.max(b,c)})},open:(a,b,c,e,f)=>{if(""===
a)throw new P.$(44);b="string"==typeof b?P.Cc(b):b;c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var g=a;else{a=rb(a);try{g=P.ea(a,{la:!(b&131072)}).node}catch(n){}}var l=!1;if(b&64)if(g){if(b&128)throw new P.$(20);}else g=P.ta(a,c,0),l=!0;if(!g)throw new P.$(44);P.Va(g.mode)&&(b&=-513);if(b&65536&&!P.ha(g.mode))throw new P.$(54);if(!l&&(c=P.Bc(g,b)))throw new P.$(c);b&512&&P.truncate(g,0);b&=-131713;e=P.mc({node:g,path:P.wa(g),flags:b,seekable:!0,position:0,da:g.da,Uc:[],
error:!1},e,f);e.da.open&&e.da.open(e);!A.logReadFiles||b&1||(P.ub||(P.ub={}),a in P.ub||(P.ub[a]=1));return e},close:a=>{if(P.Ja(a))throw new P.$(8);a.kb&&(a.kb=null);try{a.da.close&&a.da.close(a)}catch(b){throw b;}finally{P.fc(a.fd)}a.fd=null},Ja:a=>null===a.fd,na:(a,b,c)=>{if(P.Ja(a))throw new P.$(8);if(!a.seekable||!a.da.na)throw new P.$(70);if(0!=c&&1!=c&&2!=c)throw new P.$(28);a.position=a.da.na(a,b,c);a.Uc=[];return a.position},read:(a,b,c,e,f)=>{c>>>=0;if(0>e||0>f)throw new P.$(28);if(P.Ja(a))throw new P.$(8);
if(1===(a.flags&2097155))throw new P.$(8);if(P.ha(a.node.mode))throw new P.$(31);if(!a.da.read)throw new P.$(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new P.$(70);b=a.da.read(a,b,c,e,f);g||(a.position+=b);return b},write:(a,b,c,e,f,g)=>{c>>>=0;if(0>e||0>f)throw new P.$(28);if(P.Ja(a))throw new P.$(8);if(0===(a.flags&2097155))throw new P.$(8);if(P.ha(a.node.mode))throw new P.$(31);if(!a.da.write)throw new P.$(28);a.seekable&&a.flags&1024&&P.na(a,0,2);var l="undefined"!=
typeof f;if(!l)f=a.position;else if(!a.seekable)throw new P.$(70);b=a.da.write(a,b,c,e,f,g);l||(a.position+=b);return b},Ga:(a,b,c)=>{if(P.Ja(a))throw new P.$(8);if(0>b||0>=c)throw new P.$(28);if(0===(a.flags&2097155))throw new P.$(8);if(!P.isFile(a.node.mode)&&!P.ha(a.node.mode))throw new P.$(43);if(!a.da.Ga)throw new P.$(138);a.da.Ga(a,b,c)},La:(a,b,c,e,f,g)=>{b>>>=0;if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new P.$(2);if(1===(a.flags&2097155))throw new P.$(2);if(!a.da.La)throw new P.$(43);
return a.da.La(a,b,c,e,f,g)},Oa:(a,b,c,e,f)=>a&&a.da.Oa?a.da.Oa(a,b,c>>>0,e,f):0,od:()=>0,nb:(a,b,c)=>{if(!a.da.nb)throw new P.$(59);return a.da.nb(a,b,c)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=P.open(a,b.flags);a=P.stat(a).size;var f=new Uint8Array(a);P.read(e,f,0,a,0);"utf8"===b.encoding?c=L(f,0):"binary"===b.encoding&&(c=f);P.close(e);return c},writeFile:(a,
b,c={})=>{c.flags=c.flags||577;a=P.open(a,c.flags,c.mode);if("string"==typeof b){var e=new Uint8Array(Ea(b)+1);b=N(b,e,0,e.length);P.write(a,e,0,b,void 0,c.dc)}else if(ArrayBuffer.isView(b))P.write(a,b,0,b.byteLength,void 0,c.dc);else throw Error("Unsupported data type");P.close(a)},cwd:()=>P.Fb,chdir:a=>{a=P.ea(a,{la:!0});if(null===a.node)throw new P.$(44);if(!P.ha(a.node.mode))throw new P.$(54);var b=P.Aa(a.node,"x");if(b)throw new P.$(b);P.Fb=a.path},ic:()=>{P.mkdir("/tmp");P.mkdir("/home");P.mkdir("/home/web_user")},
hc:()=>{P.mkdir("/dev");P.wb(P.ya(1,3),{read:()=>0,write:(b,c,e,f)=>f});P.Ya("/dev/null",P.ya(1,3));wb(P.ya(5,0),zb);wb(P.ya(6,0),Ab);P.Ya("/dev/tty",P.ya(5,0));P.Ya("/dev/tty1",P.ya(6,0));var a=tb();P.ua("/dev","random",a);P.ua("/dev","urandom",a);P.mkdir("/dev/shm");P.mkdir("/dev/shm/tmp")},kc:()=>{P.mkdir("/proc");var a=P.mkdir("/proc/self");P.mkdir("/proc/self/fd");P.ga({ga:()=>{var b=P.createNode(a,"fd",16895,73);b.aa={lookup:(c,e)=>{var f=P.Ia(+e);if(!f)throw new P.$(8);c={parent:null,ga:{Tb:"fake"},
aa:{readlink:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},lc:()=>{A.stdin?P.ua("/dev","stdin",A.stdin):P.symlink("/dev/tty","/dev/stdin");A.stdout?P.ua("/dev","stdout",null,A.stdout):P.symlink("/dev/tty","/dev/stdout");A.stderr?P.ua("/dev","stderr",null,A.stderr):P.symlink("/dev/tty1","/dev/stderr");P.open("/dev/stdin",0);P.open("/dev/stdout",1);P.open("/dev/stderr",1)},Ib:()=>{P.$||(P.$=function(a,b){this.node=b;this.Lc=function(c){this.ka=c};this.Lc(a);this.message="FS error"},
P.$.prototype=Error(),P.$.prototype.constructor=P.$,[44].forEach(a=>{P.ib[a]=new P.$(a);P.ib[a].stack="<generic error, no stack>"}))},Oc:()=>{P.Ib();P.oa=Array(4096);P.ga(X,{},"/");P.ic();P.hc();P.kc();P.qc={MEMFS:X}},Ba:(a,b,c)=>{P.Ba.mb=!0;P.Ib();A.stdin=a||A.stdin;A.stdout=b||A.stdout;A.stderr=c||A.stderr;P.lc()},sd:()=>{P.Ba.mb=!1;for(var a=0;a<P.streams.length;a++){var b=P.streams[a];b&&P.close(b)}},jb:(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},bd:(a,b)=>{a=P.fb(a,b);return a.exists?a.object:
null},fb:(a,b)=>{try{var c=P.ea(a,{la:!b});a=c.path}catch(f){}var e={Wa:!1,exists:!1,error:0,name:null,path:null,object:null,Fc:!1,Hc:null,Gc:null};try{c=P.ea(a,{parent:!0}),e.Fc=!0,e.Hc=c.path,e.Gc=c.node,e.name=U(a),c=P.ea(a,{la:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.Wa="/"===c.path}catch(f){e.error=f.ka}return e},Zc:(a,b)=>{a="string"==typeof a?a:P.wa(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=V(a,c);try{P.mkdir(e)}catch(f){}a=e}}return e},
jc:(a,b,c,e,f)=>{a=V("string"==typeof a?a:P.wa(a),b);return P.create(a,P.jb(e,f))},Eb:(a,b,c,e,f,g)=>{var l=b;a&&(a="string"==typeof a?a:P.wa(a),l=b?V(a,b):a);a=P.jb(e,f);l=P.create(l,a);if(c){if("string"==typeof c){b=Array(c.length);e=0;for(f=c.length;e<f;++e)b[e]=c.charCodeAt(e);c=b}P.chmod(l,a|146);b=P.open(l,577);P.write(b,c,0,c.length,0,g);P.close(b);P.chmod(l,a)}return l},ua:(a,b,c,e)=>{a=V("string"==typeof a?a:P.wa(a),b);b=P.jb(!!c,!!e);P.ua.qb||(P.ua.qb=64);var f=P.ya(P.ua.qb++,0);P.wb(f,
{open:g=>{g.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(g,l,n,t)=>{for(var m=0,p=0;p<t;p++){try{var x=c()}catch(z){throw new P.$(29);}if(void 0===x&&0===m)throw new P.$(6);if(null===x||void 0===x)break;m++;l[n+p]=x}m&&(g.node.timestamp=Date.now());return m},write:(g,l,n,t)=>{for(var m=0;m<t;m++)try{e(l[n+m])}catch(p){throw new P.$(29);}t&&(g.node.timestamp=Date.now());return m}});return P.Ya(a,b,f)},Lb:a=>{if(a.ob||a.yc||a.link||a.ba)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(oa)try{a.ba=yb(oa(a.url),!0),a.fa=a.ba.length}catch(b){throw new P.$(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Yc:(a,b,c,e,f)=>{function g(){this.pb=!1;this.va=[]}g.prototype.get=function(m){if(!(m>this.length-1||0>m)){var p=m%this.chunkSize;return this.Ob(m/this.chunkSize|0)[p]}};g.prototype.bc=function(m){this.Ob=m};g.prototype.Cb=function(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+
c+". Status: "+m.status);var p=Number(m.getResponseHeader("Content-length")),x,z=(x=m.getResponseHeader("Accept-Ranges"))&&"bytes"===x;m=(x=m.getResponseHeader("Content-Encoding"))&&"gzip"===x;var k=1048576;z||(k=p);var u=this;u.bc(y=>{var D=y*k,J=(y+1)*k-1;J=Math.min(J,p-1);if("undefined"==typeof u.va[y]){var jc=u.va;if(D>J)throw Error("invalid range ("+D+", "+J+") or no bytes requested!");if(J>p-1)throw Error("only "+p+" bytes available! programmer error!");var E=new XMLHttpRequest;E.open("GET",
c,!1);p!==k&&E.setRequestHeader("Range","bytes="+D+"-"+J);E.responseType="arraybuffer";E.overrideMimeType&&E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);if(!(200<=E.status&&300>E.status||304===E.status))throw Error("Couldn't load "+c+". Status: "+E.status);D=void 0!==E.response?new Uint8Array(E.response||[]):yb(E.responseText||"",!0);jc[y]=D}if("undefined"==typeof u.va[y])throw Error("doXHR failed!");return u.va[y]});if(m||!p)k=p=1,k=p=this.Ob(0).length,xa("LazyFiles on gzip forces download of the whole file when length is accessed");
this.ac=p;this.$b=k;this.pb=!0};if("undefined"!=typeof XMLHttpRequest){if(!C)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new g;Object.defineProperties(l,{length:{get:function(){this.pb||this.Cb();return this.ac}},chunkSize:{get:function(){this.pb||this.Cb();return this.$b}}});l={ob:!1,ba:l}}else l={ob:!1,url:c};var n=P.jc(a,b,l,e,f);l.ba?n.ba=l.ba:l.url&&(n.ba=null,n.url=l.url);Object.defineProperties(n,{fa:{get:function(){return this.ba.length}}});
var t={};Object.keys(n.da).forEach(m=>{var p=n.da[m];t[m]=function(){P.Lb(n);return p.apply(null,arguments)}});t.read=(m,p,x,z,k)=>{P.Lb(n);m=m.node.ba;if(k>=m.length)return 0;z=Math.min(m.length-k,z);if(m.slice)for(var u=0;u<z;u++)p[x+u]=m[k+u];else for(u=0;u<z;u++)p[x+u]=m.get(k+u);return z};n.da=t;return n},$c:(a,b,c,e,f,g,l,n,t,m)=>{function p(z){function k(u){m&&m();n||P.Eb(a,b,u,e,f,t);g&&g();Va()}Db.hd(z,x,k,()=>{l&&l();Va()})||k(z)}var x=b?W(V(a,b)):a;Ua();"string"==typeof c?Cb(c,z=>p(z),
l):p(c)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,zb:()=>"EM_FS_"+window.location.pathname,Ab:20,Fa:"FILE_DATA",ud:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var e=P.indexedDB();try{var f=e.open(P.zb(),P.Ab)}catch(g){return c(g)}f.onupgradeneeded=()=>{xa("creating db");f.result.createObjectStore(P.Fa)};f.onsuccess=()=>{var g=f.result.transaction([P.Fa],"readwrite"),l=g.objectStore(P.Fa),n=0,t=0,m=a.length;a.forEach(p=>{p=l.put(P.fb(p).object.ba,p);
p.onsuccess=()=>{n++;n+t==m&&(0==t?b():c())};p.onerror=()=>{t++;n+t==m&&(0==t?b():c())}});g.onerror=c};f.onerror=c},jd:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var e=P.indexedDB();try{var f=e.open(P.zb(),P.Ab)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=()=>{var g=f.result;try{var l=g.transaction([P.Fa],"readonly")}catch(x){c(x);return}var n=l.objectStore(P.Fa),t=0,m=0,p=a.length;a.forEach(x=>{var z=n.get(x);z.onsuccess=()=>{P.fb(x).exists&&P.unlink(x);P.Eb(sb(x),U(x),z.result,!0,!0,!0);t++;
t+m==p&&(0==m?b():c())};z.onerror=()=>{m++;t+m==p&&(0==m?b():c())}});l.onerror=c};f.onerror=c}},Eb=void 0;function Y(){Eb+=4;return w()[Eb-4>>2>>>0]}function Z(a){a=P.Ia(a);if(!a)throw new P.$(8);return a}
function Fb(a,b,c){if(G)return T(2,1,a,b,c);Eb=c;try{var e=Z(a);switch(b){case 0:var f=Y();return 0>f?-28:P.open(e.path,e.flags,0,f).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=Y(),e.flags|=f,0;case 5:return f=Y(),h.buffer!=q&&r(h.buffer),Ha[f+0>>1>>>0]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return w()[Gb()>>2>>>0]=28,-1;default:return-28}}catch(g){if("undefined"==typeof P||!(g instanceof P.$))throw g;return-g.ka}}
function Hb(a,b){if(G)return T(3,1,a,b);try{if(0===b)return-28;var c=P.cwd();if(b<Ea(c)+1)return-68;N(c,v(),a,b);return a}catch(e){if("undefined"==typeof P||!(e instanceof P.$))throw e;return-e.ka}}
function Ib(a,b,c){if(G)return T(4,1,a,b,c);Eb=c;try{var e=Z(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var f=Y();return w()[f>>2>>>0]=0;case 21520:return e.tty?-28:-59;case 21531:return f=Y(),P.nb(e,b,f);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:K("bad ioctl syscall "+b)}}catch(g){if("undefined"==typeof P||!(g instanceof P.$))throw g;return-g.ka}}
function Jb(a,b,c){if(G)return T(5,1,a,b,c);Eb=c;try{var e=M(a),f=c?Y():0;return P.open(e,b,f).fd}catch(g){if("undefined"==typeof P||!(g instanceof P.$))throw g;return-g.ka}}function T(a,b){var c=arguments.length-2,e=arguments;return bb(function(){for(var f=O(8*c),g=f>>3,l=0;l<c;l++){var n=e[2+l];da()[g+l>>>0]=n}return Kb(a,c,f,b)})}var Lb=[];
function Mb(a,b,c,e){bb(function(){var f=O(12),g=0;if(b){g=Ea(b)+1;var l=Nb(g);N(b,v(),l,g);g=l}w()[f>>2>>>0]=g;w()[f+4>>2>>>0]=c;w()[f+8>>2>>>0]=e;Ob(a,657457152,0,g,f)})}var Pb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function Qb(a){a=2<a?M(a):a;return Pb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}
function Rb(a,b,c){var e=Qb(a);if(!e)return-4;e.Ua&&(w()[e.Ua>>2>>>0]=b,w()[e.Ua+4>>2>>>0]=c);if(e.Ub||!e.Xc)e.Ub&&(e=e.Ub),a=!1,e.Ta&&e.Ta.Sa&&(a=e.Ta.Sa.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===e.width&&a[3]===e.height),e.width=b,e.height=c,a&&e.Ta.Sa.viewport(0,0,b,c);else return e.Ua?(e=w()[e.Ua+8>>2>>>0],a=a?M(a):"",Mb(e,a,b,c),1):-4;return 0}function Sb(a,b,c){return G?T(6,1,a,b,c):Rb(a,b,c)}
function Tb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,g){b.drawArraysInstancedANGLE(c,e,f,g)},a.drawElementsInstanced=function(c,e,f,g,l){b.drawElementsInstancedANGLE(c,e,f,g,l)})}
function Ub(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Vb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}
function Wb(a,b){a.va||(a.va=a.getContext,a.getContext=function(e,f){f=a.va(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Xb(c,b):0}function Xb(a,b){var c=Nb(8);w()[c+4>>2>>>0]=ib();var e={gd:c,attributes:b,version:b.zc,Sa:a};a.canvas&&(a.canvas.Ta=e);("undefined"==typeof b.Hb||b.Hb)&&Yb(e);return c}
function Yb(a){a||(a=Zb);if(!a.uc){a.uc=!0;var b=a.Sa;Tb(b);Ub(b);Vb(b);b.ad=b.getExtension("EXT_disjoint_timer_query");b.nd=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Zb,$b=["default","low-power","high-performance"],ac={};
function bc(){if(!cc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ka||"./this.program"},b;for(b in ac)void 0===ac[b]?delete a[b]:a[b]=ac[b];var c=[];for(b in a)c.push(b+"="+a[b]);cc=c}return cc}var cc;
function dc(a,b){if(G)return T(7,1,a,b);var c=0;bc().forEach(function(e,f){var g=b+c;f=w()[a+4*f>>2>>>0]=g;for(g=0;g<e.length;++g)d()[f++>>0>>>0]=e.charCodeAt(g);d()[f>>0>>>0]=0;c+=e.length+1});return 0}function ec(a,b){if(G)return T(8,1,a,b);var c=bc();w()[a>>2>>>0]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});w()[b>>2>>>0]=e;return 0}function fc(a){if(G)return T(9,1,a);try{var b=Z(a);P.close(b);return 0}catch(c){if("undefined"==typeof P||!(c instanceof P.$))throw c;return c.ka}}
function gc(a,b,c,e){if(G)return T(10,1,a,b,c,e);try{a:{for(var f=Z(a),g=a=0;g<c;g++){var l=w()[b+8*g>>2>>>0],n=w()[b+(8*g+4)>>2>>>0],t=P.read(f,d(),l,n,void 0);if(0>t){var m=-1;break a}a+=t;if(t<n)break}m=a}w()[e>>2>>>0]=m;return 0}catch(p){if("undefined"==typeof P||!(p instanceof P.$))throw p;return p.ka}}
function hc(a,b,c,e,f){if(G)return T(11,1,a,b,c,e,f);try{var g=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;P.na(g,a,e);Za=[g.position>>>0,(S=g.position,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];w()[f>>2>>>0]=Za[0];w()[f+4>>2>>>0]=Za[1];g.kb&&0===a&&0===e&&(g.kb=null);return 0}catch(l){if("undefined"==typeof P||!(l instanceof P.$))throw l;return l.ka}}
function ic(a,b,c,e){if(G)return T(12,1,a,b,c,e);try{a:{for(var f=Z(a),g=a=0;g<c;g++){var l=w()[b+8*g>>2>>>0],n=w()[b+(8*g+4)>>2>>>0],t=P.write(f,d(),l,n,void 0);if(0>t){var m=-1;break a}a+=t}m=a}w()[e>>2>>>0]=m;return 0}catch(p){if("undefined"==typeof P||!(p instanceof P.$))throw p;return p.ka}}function kc(a){return 0===a%4&&(0!==a%100||0===a%400)}function lc(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var mc=[31,29,31,30,31,30,31,31,30,31,30,31],nc=[31,28,31,30,31,30,31,31,30,31,30,31];
function oc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(kc(a.getFullYear())?mc:nc)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function pc(a,b,c,e){function f(k,u,y){for(k="number"==typeof k?k.toString():k||"";k.length<u;)k=y[0]+k;return k}function g(k,u){return f(k,u,"0")}function l(k,u){function y(J){return 0>J?-1:0<J?1:0}var D;0===(D=y(k.getFullYear()-u.getFullYear()))&&0===(D=y(k.getMonth()-u.getMonth()))&&(D=y(k.getDate()-u.getDate()));return D}function n(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function t(k){k=oc(new Date(k.ja+1900,0,1),k.cb);var u=new Date(k.getFullYear()+1,0,4),y=n(new Date(k.getFullYear(),0,4));u=n(u);return 0>=l(y,k)?0>=l(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var m=w()[e+40>>2>>>0];e={Rc:w()[e>>2>>>0],Qc:w()[e+4>>2>>>0],ab:w()[e+8>>2>>>0],Ra:w()[e+12>>2>>>0],Ea:w()[e+16>>2>>>0],ja:w()[e+20>>2>>>0],bb:w()[e+
24>>2>>>0],cb:w()[e+28>>2>>>0],wd:w()[e+32>>2>>>0],Pc:w()[e+36>>2>>>0],Sc:m?M(m):""};c=M(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,
"g"),m[p]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),z="January February March April May June July August September October November December".split(" ");m={"%a":function(k){return x[k.bb].substring(0,3)},"%A":function(k){return x[k.bb]},"%b":function(k){return z[k.Ea].substring(0,3)},"%B":function(k){return z[k.Ea]},"%C":function(k){return g((k.ja+1900)/100|0,2)},"%d":function(k){return g(k.Ra,2)},"%e":function(k){return f(k.Ra,2," ")},"%g":function(k){return t(k).toString().substring(2)},
"%G":function(k){return t(k)},"%H":function(k){return g(k.ab,2)},"%I":function(k){k=k.ab;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.Ra+lc(kc(k.ja+1900)?mc:nc,k.Ea-1),3)},"%m":function(k){return g(k.Ea+1,2)},"%M":function(k){return g(k.Qc,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.ab&&12>k.ab?"AM":"PM"},"%S":function(k){return g(k.Rc,2)},"%t":function(){return"\t"},"%u":function(k){return k.bb||7},"%U":function(k){var u=new Date(k.ja+1900,0,1),y=0===u.getDay()?
u:oc(u,7-u.getDay());k=new Date(k.ja+1900,k.Ea,k.Ra);return 0>l(y,k)?g(Math.ceil((31-y.getDate()+(lc(kc(k.getFullYear())?mc:nc,k.getMonth()-1)-31)+k.getDate())/7),2):0===l(y,u)?"01":"00"},"%V":function(k){var u=new Date(k.ja+1901,0,4),y=n(new Date(k.ja+1900,0,4));u=n(u);var D=oc(new Date(k.ja+1900,0,1),k.cb);return 0>l(D,y)?"53":0>=l(u,D)?"01":g(Math.ceil((y.getFullYear()<k.ja+1900?k.cb+32-y.getDate():k.cb+1-y.getDate())/7),2)},"%w":function(k){return k.bb},"%W":function(k){var u=new Date(k.ja,0,
1),y=1===u.getDay()?u:oc(u,0===u.getDay()?1:7-u.getDay()+1);k=new Date(k.ja+1900,k.Ea,k.Ra);return 0>l(y,k)?g(Math.ceil((31-y.getDate()+(lc(kc(k.getFullYear())?mc:nc,k.getMonth()-1)-31)+k.getDate())/7),2):0===l(y,u)?"01":"00"},"%y":function(k){return(k.ja+1900).toString().substring(2)},"%Y":function(k){return k.ja+1900},"%z":function(k){k=k.Pc;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Sc},"%%":function(){return"%"}};c=c.replace(/%%/g,
"\x00\x00");for(p in m)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),m[p](e)));c=c.replace(/\0\0/g,"%");p=yb(c,!1);if(p.length>b)return 0;Ga(p,a);return p.length-1}B.Ba();function qc(a,b,c,e){a||(a=this);this.parent=a;this.ga=a.ga;this.Ma=null;this.id=P.Dc++;this.name=b;this.mode=c;this.aa={};this.da={};this.rdev=e}
Object.defineProperties(qc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},yc:{get:function(){return P.ha(this.mode)}},ob:{get:function(){return P.Va(this.mode)}}});P.Yb=qc;P.Oc();var Db,rc=[null,mb,Fb,Hb,Ib,Jb,Sb,dc,ec,fc,gc,hc,ic];function yb(a,b){var c=Array(Ea(a)+1);a=N(a,c,0,c.length);b&&(c.length=a);return c}
var uc={y:function(a){sc(a,!C,1,!ma);B.Xb()},h:function(a){G?postMessage({cmd:"cleanupThread",thread:a}):eb(a)},j:function(a,b,c,e){if("undefined"==typeof SharedArrayBuffer)return I("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(G&&0===f.length)return tc(687865856,a,b,c,e);a={Nc:c,sb:a,Ha:e,Tc:f};return G?(a.Wc="spawnThread",postMessage(a,f),0):kb(a)},e:Fb,A:Hb,l:Ib,m:Jb,u:function(){return 2097152},z:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(G)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=B.qa[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){K("")},s:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=pb();else return w()[Gb()>>2>>>0]=28,-1;w()[b>>2>>>0]=a/1E3|0;w()[b+4>>2>>>0]=a%1E3*1E6|0;return 0},g:function(){F||C||(ya||(ya={}),ya["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||
(ya["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,I("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},c:pb,B:function(a,b,c){v().copyWithin(a>>>0,b>>>0,b+c>>>0)},v:function(a,b,c){Lb.length=b;c>>=3;for(var e=0;e<b;e++)Lb[e]=da()[c+e>>>0];return(0>a?$a[-a-1]:rc[a]).apply(null,Lb)},t:function(a){var b=v().length;
a>>>=0;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);f=f.min.call(f,4294901760,e+(65536-e%65536)%65536);a:{try{h.grow(f-q.byteLength+65535>>>16);r(h.buffer);var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},w:function(a,b,c){return Qb(a)?Rb(a,b,c):Sb(a,b,c)},n:function(){throw"unwind";},x:function(a,b){b>>=2;var c=w()[b+6>>>0];b={alpha:!!w()[b>>>0],depth:!!w()[b+1>>>0],stencil:!!w()[b+2>>>0],antialias:!!w()[b+3>>>
0],premultipliedAlpha:!!w()[b+4>>>0],preserveDrawingBuffer:!!w()[b+5>>>0],powerPreference:$b[c],failIfMajorPerformanceCaveat:!!w()[b+7>>>0],zc:w()[b+8>>>0],ld:w()[b+9>>>0],Hb:w()[b+10>>>0],pc:w()[b+11>>>0],qd:w()[b+12>>>0],td:w()[b+13>>>0]};a=Qb(a);return!a||b.pc?0:Wb(a,b)},q:dc,r:ec,d:function(a){nb(a)},f:fc,k:gc,o:hc,C:ic,a:h||A.wasmMemory,p:function(a,b,c,e){return pc(a,b,c,e)},i:function(a){var b=Date.now()/1E3|0;a&&(w()[a>>2>>>0]=b);return b}};
(function(){function a(f,g){A.asm=f.exports;B.$a.push(A.asm.H);Ja=A.asm.P;La.unshift(A.asm.D);Aa=g;if(!G){var l=B.ra.length;B.ra.forEach(function(n){B.Sb(n,function(){--l||Va()})})}}function b(f){a(f.instance,f.module)}function c(f){return Ya().then(function(g){return WebAssembly.instantiate(g,e)}).then(function(g){return g}).then(f,function(g){I("failed to asynchronously prepare wasm: "+g);K(g)})}var e={a:uc};G||Ua();if(A.instantiateWasm)try{return A.instantiateWasm(e,a)}catch(f){return I("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return za||"function"!=typeof WebAssembly.instantiateStreaming||Wa()||"function"!=typeof fetch?c(b):fetch(R,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){I("wasm streaming compile failed: "+g);I("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ha);return{}})();A.___wasm_call_ctors=function(){return(A.___wasm_call_ctors=A.asm.D).apply(null,arguments)};
A._main=function(){return(A._main=A.asm.E).apply(null,arguments)};A._free=function(){return(A._free=A.asm.F).apply(null,arguments)};A._usi_command=function(){return(A._usi_command=A.asm.G).apply(null,arguments)};A._emscripten_tls_init=function(){return(A._emscripten_tls_init=A.asm.H).apply(null,arguments)};
var Bb=A._emscripten_builtin_memalign=function(){return(Bb=A._emscripten_builtin_memalign=A.asm.I).apply(null,arguments)},Gb=A.___errno_location=function(){return(Gb=A.___errno_location=A.asm.J).apply(null,arguments)};A.__emscripten_thread_crashed=function(){return(A.__emscripten_thread_crashed=A.asm.K).apply(null,arguments)};
var sc=A.__emscripten_thread_init=function(){return(sc=A.__emscripten_thread_init=A.asm.L).apply(null,arguments)},ib=A._pthread_self=function(){return(ib=A._pthread_self=A.asm.M).apply(null,arguments)},jb=A._emscripten_main_thread_process_queued_calls=function(){return(jb=A._emscripten_main_thread_process_queued_calls=A.asm.N).apply(null,arguments)},Nb=A._malloc=function(){return(Nb=A._malloc=A.asm.O).apply(null,arguments)};
A._emscripten_current_thread_process_queued_calls=function(){return(A._emscripten_current_thread_process_queued_calls=A.asm.Q).apply(null,arguments)};
var tc=A._emscripten_sync_run_in_main_thread_4=function(){return(tc=A._emscripten_sync_run_in_main_thread_4=A.asm.R).apply(null,arguments)},Kb=A._emscripten_run_in_main_runtime_thread_js=function(){return(Kb=A._emscripten_run_in_main_runtime_thread_js=A.asm.S).apply(null,arguments)},Ob=A._emscripten_dispatch_to_thread_=function(){return(Ob=A._emscripten_dispatch_to_thread_=A.asm.T).apply(null,arguments)},gb=A.__emscripten_thread_free_data=function(){return(gb=A.__emscripten_thread_free_data=A.asm.U).apply(null,
arguments)};A.__emscripten_thread_exit=function(){return(A.__emscripten_thread_exit=A.asm.V).apply(null,arguments)};
var lb=A._emscripten_stack_set_limits=function(){return(lb=A._emscripten_stack_set_limits=A.asm.W).apply(null,arguments)},cb=A.stackSave=function(){return(cb=A.stackSave=A.asm.X).apply(null,arguments)},db=A.stackRestore=function(){return(db=A.stackRestore=A.asm.Y).apply(null,arguments)},O=A.stackAlloc=function(){return(O=A.stackAlloc=A.asm.Z).apply(null,arguments)},hb=A.__emscripten_allow_main_runtime_queued_calls=29552;
A.ccall=function(a,b,c,e){var f={string:function(m){var p=0;if(null!==m&&void 0!==m&&0!==m){var x=(m.length<<2)+1,z=p=O(x);N(m,v(),z,x)}return p},array:function(m){var p=O(m.length);Ga(m,p);return p}};a=A["_"+a];var g=[],l=0;if(e)for(var n=0;n<e.length;n++){var t=f[c[n]];t?(0===l&&(l=cb()),g[n]=t(e[n])):g[n]=e[n]}c=a.apply(null,g);return c=function(m){0!==l&&db(l);return"string"===b?M(m):"boolean"===b?!!m:m}(c)};A.keepRuntimeAlive=ua;A.FS=P;A.PThread=B;A.PThread=B;A.wasmMemory=h;A.ExitStatus=ta;var vc;
function ta(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ta=function wc(){vc||xc();vc||(Ta=wc)};
function xc(a){function b(){if(!vc&&(vc=!0,A.calledRun=!0,!Ba)){Pa();G||Qa(Ma);fa(A);if(A.onRuntimeInitialized)A.onRuntimeInitialized();if(yc){var c=a,e=A._main;c=c||[];var f=c.length+1,g=O(4*(f+1));w()[g>>>2]=Fa(ka);for(var l=1;l<f;l++)w()[(g>>2)+l>>>0]=Fa(c[l-1]);w()[(g>>2)+f>>>0]=0;try{var n=e(f,g);nb(n,!0)}catch(t){fb(t)}finally{}}if(!G){if(A.postRun)for("function"==typeof A.postRun&&(A.postRun=[A.postRun]);A.postRun.length;)c=A.postRun.shift(),Na.unshift(c);Qa(Na)}}}a=a||ja;if(!(0<Q))if(G)fa(A),
Pa(),postMessage({cmd:"loaded"});else{if(A.preRun)for("function"==typeof A.preRun&&(A.preRun=[A.preRun]);A.preRun.length;)Ra();Qa(Ka);0<Q||(A.setStatus?(A.setStatus("Running..."),setTimeout(function(){setTimeout(function(){A.setStatus("")},1);b()},1)):b())}}A.run=xc;function nb(a,b){if(!b&&G)throw mb(a),"unwind";ua()||G||B.xb();if(!ua()){B.xb();if(A.onExit)A.onExit(a);Ba=!0}la(a,new ta(a))}if(A.preInit)for("function"==typeof A.preInit&&(A.preInit=[A.preInit]);0<A.preInit.length;)A.preInit.pop()();
var yc=!0;A.noInitialRun&&(yc=!1);xc();


  return YaneuraOu_HalfKPvm_noeval.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = YaneuraOu_HalfKPvm_noeval;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return YaneuraOu_HalfKPvm_noeval; });
else if (typeof exports === 'object')
  exports["YaneuraOu_HalfKPvm_noeval"] = YaneuraOu_HalfKPvm_noeval;
